### ISSUE TITLE
Reportar áreas por municipio para escenario E00 #MEGADAPT

### ISSUE THREAD

**Issue by marcoajh** [PaolaGomezPriego/planeacion-colaborativa#163]
Aplicar la mascara de zonas federales y reportar áreas (m²) por municipio

**Comment by edithvilla** [comment]
@marcoajh me proporcionará los nuevos datos por municipio

**Comment by PaolaGomezPriego** [comment]
Se cierra hasta que se haga análisis de precisión de SLEUTH.
