### ISSUE TITLE
Revisar Solicitud de trabajo de Diseño LANCIS

### ISSUE THREAD

**Issue by ovisnigra** [PaolaGomezPriego/planeacion-colaborativa#365]
Hacer versión en HTML de la solicitud de trabajo de diseño, con miras a que en un futuro se puedan llenar y mandar por la Web.

**Comment by ovisnigra** [comment]
Revisar "Forms" e "Inputs" de Bootstrap:
https://www.w3schools.com/bootstrap/bootstrap_forms_inputs.asp

**Comment by ovisnigra** [comment]
Solicitud de diseño en Google Forms: https://goo.gl/forms/AyvyljuRGOLII7VX2
Solicitud de correcciones: https://goo.gl/forms/TWUYvrRWy62GeBJk2

**Comment by ovisnigra** [comment]
Después de las primeras pruebas con Edí:

1.. Hice ajustes a la solicitud de correcciones.
2. Hay que añadir a Paola como receptora de notificaciones
2. hay que seguir haciendo pruebas.

**Comment by ovisnigra** [comment]
1. A partir de ahora, la solicitud de trabajo de diseño puede consultarse y llenarse en el siguiente link: https://goo.gl/forms/9Os3VhEsh9Yw6Hxo2
Y la solicitud de correcciones, aquí: https://goo.gl/forms/O8GMoLF4GbOPwhgq1
---
2. Pregunta para @edithvilla :
¿según los protocolos de la certificación ISO, cómo se llenan la clave y número para estas solicitudes?
---
3. Sigo haciendo pruebas.

**Comment by ovisnigra** [comment]
Es el momento de revisar y hacer pruebas. Pueden llenar un par de formularios para poner a prueba el sistema.

- [Liga al formulario de solicitud](https://docs.google.com/forms/d/e/1FAIpQLSdB_voN1q7SNMsaMvcEYSzMbiVClv05A9gss_z4M8ewT7R9wQ/viewform?usp=sf_link)
- [Liga al formulario de correcciones]( https://docs.google.com/forms/d/e/1FAIpQLScYX_1AKw6hg7VH8qV7P-qoQiJGuwamTqwJipNZxbkNautZzA/viewform?usp=sf_link)
- [Liga a la base de datos de las solicitudes](https://docs.google.com/spreadsheets/d/10VRhkBeX5culxvIMsY2bmQrCuv52PiMNnHnc8FDR1jE/edit?usp=sharing)
- [Liga a un documento de muestra generado mediante el formulario y la base de datos](https://drive.google.com/file/d/1MIw61HY9kiitVcBPJo2pzTVtmDqPL8qG/view?usp=sharing)

**Comment by ovisnigra** [comment]
solicitud final
https://docs.google.com/forms/d/e/1FAIpQLSfiIiApB2_MZ7rdXzqdCU5xLo7eGDBSzsUUbZYtQ-TJ4YcckQ/viewform?usp=sf_link

base de datos
https://docs.google.com/spreadsheets/d/1fK5PWsCktJnTJJOQbPU_XoyeBsgriV3LFlX6VRPtX4A/edit?usp=sharing

**Comment by ovisnigra** [comment]
queda abierto el issue, pos unos días, por si hay cambios o correcciones

**Comment by PaolaGomezPriego** [comment]
terminada
