### ISSUE TITLE
Organizar carpeta de PN para el dropbox #PN

### ISSUE THREAD

**Issue by PaolaGomezPriego** [PaolaGomezPriego/planeacion-colaborativa#424]

**Comment by edithvilla** [comment]
@PaolaGomezPriego 
Ya hay una propuesta de organización para PN y se encuentra en el dropbox

C:\Dropbox (LNCS)\PN

aún hay un par de consultas que necesito hacerte, por ejemplo:
1. plataforma_versatile mejor ponerlo en procesamiento

**Comment by edithvilla** [comment]
Ya la organicé, solo falta:
1. agregar los readme por carpeta
2. agregar y acomodar la carpeta de Pacifico Norte que se encuentra en el dropbox

**Comment by edithvilla** [comment]
Ya está lista la carpeta PN, en enero se hará el paso al dropbox

**Comment by edithvilla** [comment]
ya está la carpeta de PN en el dropbox lista
