### ISSUE TITLE
Hacer plantilla para tarjetas personales #LANCIS

### ISSUE THREAD

**Issue by ovisnigra** [PaolaGomezPriego/planeacion-colaborativa#430]
Hacer plantilla para tarjetas personales de LANCIS. 

La plantilla quedará guardada en:

` \ORGANIZACION_APC\plantillas\plantillas_tarjetas_lancis`

**Comment by PaolaGomezPriego** [comment]
no se inició con verbo!

**Comment by ovisnigra** [comment]
Lista plantilla

` \ORGANIZACION_APC\plantillas\plantillas_tarjetas_lancis\plantilla_tarjetas_lancis.ait`

En la misma plantilla están incorporadas las instrucciones de uso, estaría bien hacer una prueba para ver si las instrucciones son claras.

**Comment by PaolaGomezPriego** [comment]
No puedo abrir el formato ait

**Comment by ovisnigra** [comment]
es archivo de illustrator ¿no te lo instalé?

**Comment by ovisnigra** [comment]
En la misma carpeta: 
\ORGANIZACION_APC\apc_plantillas\plantillas_tarjetas_lancis\plantilla_tarjetas_lancis.ait

incorporé un PDF como muestra de las instrucciones y un README.txt con metadatos y comentarios.

**Comment by ovisnigra** [comment]
cambiar formato 9 x 5 y cerrar

**Comment by ovisnigra** [comment]
listo. 

_cerratum est_
