### ISSUE TITLE
Renombrar artículos de acuerdo a formato estipulado en la bibliografia LANCIS

### ISSUE THREAD

**Issue by Didigar** [PaolaGomezPriego/planeacion-colaborativa#448]

**Comment by Didigar** [comment]
Hoy 22 de enero, recibí nuevas instrucciones de que ésta debe ser agregada a la carpeta de Lak en dropbox con el formato debido (lo mas que se pueda para que ya no me tome más tiempo).

**Comment by PaolaGomezPriego** [comment]
Issues por carpeta de trabajo
