### ISSUE TITLE
Crear capa en /Layers de cuencas bajas y altas #megadapt

### ISSUE THREAD

**Issue by PaolaGomezPriego** [PaolaGomezPriego/planeacion-colaborativa#450]

**Comment by marcoajh** [comment]
@PaolaGomezPriego @abaezacastro 
La capa ya está lista, la ubicación es:
https://www.dropbox.com/home/MEGADAPT_integracion2/Layers/final/low_hig.shp

**Comment by abaezacastro** [comment]
@marcoajh puedes hacer la capa a escala de ageb porfa?
gracias

**Comment by marcoajh** [comment]
@abaezacastro 
Listo, la capa low_hig_v1.shp está a nivel de AGEB. La ubicación en dropbox es la misma:
MEGADAPT_integracion2/Layers/final/low_hig_v1.shp
