### ISSUE TITLE
Crear capa de % de capas sin inodoro  y agregar a Layers #Megadapt

### ISSUE THREAD

**Issue by PaolaGomezPriego** [PaolaGomezPriego/planeacion-colaborativa#483]
@aleestrada si Marco no tiene los datos, se los puedes proporcionar por favor?
Avisar a @abaezacastro en cuanto esté lista.

**Comment by PaolaGomezPriego** [comment]
a nivel de ageb

**Comment by marcoajh** [comment]
Ya está, revisar issue 485
https://github.com/sostenibilidad-unam/planeacion-colaborativa/issues/485
