### ISSUE TITLE
Crear capa de % de casas sin piso de tierra  y agregar a Layers #Megadapt

### ISSUE THREAD

**Issue by PaolaGomezPriego** [PaolaGomezPriego/planeacion-colaborativa#484]
A nivel de AGEB.
@aleestrada si Marco no tiene los datos, se los puedes proporcionar por favor?
Avisar a @abaezacastro en cuanto esté lista.

**Comment by aleestrada** [comment]
Se entregó a Marco los datos necesarios para realizar la capa

**Comment by marcoajh** [comment]
@PaolaGomezPriego @abaezacastro  La capa está lista.
https://github.com/sostenibilidad-unam/layers/issues/63
Sólo queda pendiente la parte de metodología en los metadatos, a cargo de @aleestrada
