### ISSUE TITLE
Crear capa el promedio de escolaridad y agregar a Layers #Megadapt

### ISSUE THREAD

**Issue by PaolaGomezPriego** [PaolaGomezPriego/planeacion-colaborativa#486]
@aleestrada si Marco no tiene los datos, se los puedes proporcionar por favor?
Avisar a @abaezacastro en cuanto esté lista.
a nivel de ageb

**Comment by aleestrada** [comment]
Se proporcionaron a @marcoajh los datos necesarios para realizar la capa

**Comment by marcoajh** [comment]
@PaolaGomezPriego @abaezacastro  La capa está lista.
https://github.com/sostenibilidad-unam/layers/issues/64
Sólo queda pendiente la parte de metodología en los metadatos, a cargo de @aleestrada
