### ISSUE TITLE
Crear funciones de valor continuas hipotéticas para modelo ABM #megadapt

### ISSUE THREAD

**Issue by PaolaGomezPriego** [PaolaGomezPriego/planeacion-colaborativa#491]
Con base en plataforma de @serranoycandela

**Comment by PaolaGomezPriego** [comment]
Urgen para que @abaezacastro pueda programarlas

**Comment by PaolaGomezPriego** [comment]
Yosune coordina para que los especialistas den la información. Apoyan @edithvilla  @bibianamonsivais y @marcoajh

**Comment by abaezacastro** [comment]
Ya estan definidas las funciones de valor continuas para SACMEX definidas por Andres y Hallie.

**Comment by PaolaGomezPriego** [comment]
Se cierra el issue. El siguiente proceso se hace directamente con la gente de SACMEX.
