### ISSUE TITLE
Generación de las nuevas gráficas de MIA con bases de datos actualizados  #OIPA

### ISSUE THREAD

**Issue by Didigar** [PaolaGomezPriego/planeacion-colaborativa#495]
@PaolaGomezPriego 
Aqui está la nueva carpeta que contiene únicamente los png de las gráficas incluyendo las nuevas .. dropbox/Doctorado/Procesamiento/figuras_graficas....
Quedo pendiente de Vo.Bo.

**Comment by PaolaGomezPriego** [comment]
así no se escriben los issues. no incluye una acción ni el nombre del proyecto!

**Comment by Didigar** [comment]
Originalmente no era un issue sólo quería indicar donde están las imágenes... @Nayita me hizo el issue....lo voy a convertir a issue entonces ...

**Comment by Didigar** [comment]
Se re abrió issue para agregar una gráfica más... Disposición de resolutivo con reloución en gaceta, evaluadas por DGIRA y Delegación.
Lista en carpeta de Paola Doctorado dropbox.
