### ISSUE TITLE
Repartir y organizar las carpetas del dropbox

### ISSUE THREAD

**Issue by edithvilla** [PaolaGomezPriego/planeacion-colaborativa#504]
@Nayita , @Didigar @ovisnigra 

hay que repartirnos las carpetas  del dropbox

la lista se encuentra en el google drive, la hoja de Dropbox_no_organizado

**Comment by edithvilla** [comment]
Preguntar sobre las carpetas:
InfoCCUD mandaré un correo a Abril para preguntarle sobre esta carpeta
Arturo codigos python, le preguntaré a Fidel y a Luis sobre el uso de esta carpeta.

**Comment by edithvilla** [comment]
@ovisnigra estamos organizando el dropbox qué va a pasar con tus dos carpetas???
1. Diseño gráfico LANCIS (Respaldo Sergio)
2. Material grafico-editorial LANCIS

se van a reubicar en otras carpetas, o se van a quedar en la raíz del dropbox??

**Comment by PaolaGomezPriego** [comment]
Poner issues mas específicos!

**Comment by ovisnigra** [comment]
@edithvilla 
- La carpeta de **Diseño Gráfico LANCIS,** aún no sé que hacer con ella, si conservarla como respaldo o repartirla en las carpetas de proyecto. Tengo que consultarlo hoy con Paola.
- La carpeta **Materil graico-editorial** ya la voy a eliminar, su contenido se movió a la carpeta de ORGANIZACIÖN_APC

**Comment by Nayita** [comment]
Ya terminé mis carpetas asignadas. Continuaré con las que no han sido asignadas.

**Comment by edithvilla** [comment]
ya está hecho
