### ISSUE TITLE
hacer plantilla de word para trabajos de posgrado #PCS

### ISSUE THREAD

**Issue by ovisnigra** [PaolaGomezPriego/planeacion-colaborativa#506]
lista para revisión. según la solicitud y archivo de instrucciones queda guardada en

`Dropbox (LNCS)\ORGANIZACION_APC\apc_plantillas\plantillas_posgrado\plantilla_pcs.dotx`

**Comment by PaolaGomezPriego** [comment]
Los subtítulos no los pusiste como VERSALITAS. Trataré de corregirlo

**Comment by PaolaGomezPriego** [comment]
y pusiste NEGRITAS!!!!

**Comment by ovisnigra** [comment]
- Es un añejo problema de traducción al cual contribuyó Word confundiendo a todo el mundo. Las versalitas son, por así decirlo unas "mayúsculas chiquitas". Tal vez querías todas en mayúsculas (en ese caso el término serían "Versales". 
- Sí puse negritas pa distinguir el primer nivel de el siguiente (como no me especificaste cómo querías los siguientes subniveles de títulos, me tomé la libertad de improvisar.
- Si no has podido arreglarlo, avísame pa que lo corrija.

Saludos
