### ISSUE TITLE
Revisar Convcatoria Servicio Social 2018-2

### ISSUE THREAD

**Issue by ovisnigra** [PaolaGomezPriego/planeacion-colaborativa#515]
Se aumentaron carreras en la convocatoria. Nadia me pidió que revisara el formato par una mejor distribucón.

El archivo está en: 

`Dropbox (LNCS)\OTROS\servicio_social\convocatoria_servicio_social_2018-2.ai`

**Comment by ovisnigra** [comment]
@Nayita , sobre tu solicitud, tengo un par de dudas y observaciones:

1. Que me confirmes si hay que añadir "Ciencias Políticas y Administración Pública" com
o un solo rubro o si son dos separados (Ciencias + Admón). Por como llenaste la solicitud, se entiende que es solo uno.

2. Que corrijas la ubicación del archivo para que quede bien llenado en la solicitud. Pusiste:
 https://www.dropbox.com/home/OTROS/servicio_social
 es suficiente con que pongas la ruta a partir de la carpeta pricipal (se entiende que todas están en buestro DropBox. Así: 
 `OTROS/servicio_social/nombre_del_archivo.ai`

Gracias de antemano. Ya está avanzado, en cuanto me mandes de nuevo te lo mando de vuelta (si es antes de las 12 plis, porque he de salir).

Saludos

**Comment by Nayita** [comment]
@ovisnigra 
1. Te confirmo, es un solo rubro. Así se llama la carrera : "Ciencias Políticas y Administración Pública"
2. Solicitud corregida y enviada 
3. Archivo actualizado en Dropbox

Gracias

Saludos

**Comment by ovisnigra** [comment]
perfecto. gracias. en un rato más ya queda

**Comment by ovisnigra** [comment]
Listo queda el archivo con la corrección en:

`OTROS/servicio_social/convocatoria_servicio_social_2018-2.ai`

OJO: Veo que falta modificar las fechas (para envío de email, la de entrevistas y la del curso) en el texto de la esquina inferior izquierda. no se les vaya a quedar así.

Saludos

**Comment by Nayita** [comment]
@ovisnigra 
Si Sergio, gracias
Listo, caso cerrado ;)

Saludos
