### ISSUE TITLE
Pasar a ORGANIZACION_APC la carpeta de repositorio_r 

### ISSUE THREAD

**Issue by Didigar** [PaolaGomezPriego/planeacion-colaborativa#521]

**Comment by Didigar** [comment]
listo

**Comment by Didigar** [comment]
@PaolaGomezPriego @yosunemiquela 
Aquí está la carpeta de repositorio r en donde irá el repositorio de bibliotecas 
dropbox/ORGANIZACION_APC/apc_repositorio_r

**Comment by PaolaGomezPriego** [comment]
@yosunemiquela  nos puedes poner por favor las librerías de R en 
dropbox/ORGANIZACION_APC/apc_repositorio_r/librerias
