### ISSUE TITLE
Llenar el excel con nuestra información para #Convocatoria CONACYT

### ISSUE THREAD

**Issue by Didigar** [PaolaGomezPriego/planeacion-colaborativa#528]
@marcoajh  @Nayita @bibianamonsivais @edithvilla @PaolaGomezPriego 

Les dejo el formato en mi carpeta de dropbox (dega) ... hay tres columnas( Producto que generará, Actividades específicas que realizará dentro del proyecto e Información relevante del participante) que vamos a terminar de llenar mañana, por mientras mándenme por favor sus datos hoy 24ene2018 para juntarlos y ya mañana completar las columnas que faltan ....
dropbox/CARPETAS_TRABAJO/dega

**Comment by Didigar** [comment]
@marcoajh @Nayita @bibianamonsivais @edithvilla @PaolaGomezPriego
Ya llene una hoja de excel, úsenla como ejemplo, está en mi carpeta de trabajo en dropbox también, tiene mi nombre....

**Comment by Nayita** [comment]
@Didigar 
Va el archivo...

**Comment by Nayita** [comment]
@Didigar 

Te lo envié a tu correo.

Saludos

**Comment by bibianamonsivais** [comment]
Ya te lo envié a tu correo

**Comment by Didigar** [comment]
@Nayita @bibianamonsivais 
Recibidos y agregados, estamos pendientes de revisión y cambios...

**Comment by marcoajh** [comment]
@Didigar 
Ya te mandé el archivo por correo.

**Comment by edithvilla** [comment]
@Didigar ya te lo mandé por correo, solo tengo la duda de la columna k (Institución) yo puse donde hice la maestria

**Comment by Didigar** [comment]
@edithvilla 
Recibido y agregado, yo supongo que si va la institución del último grado que pusiste, pero mañana afinamos detalles

**Comment by Didigar** [comment]
@edithvilla no he recibido el correo con tu excel

**Comment by Didigar** [comment]
@marcoajh @edithvilla 
ya recibí sus excel y adjunte sus datos...
Edith puse un ejemplo de las tres columnas que no sabíamos como llenar en un excel que está en la misma carpeta, Luis nos dió unos ejemplos de lo que pusiéramos, si lo puedes agregar sobre los programas que manejas y que actividades realizas porfa 
el excel que ya tiene nuestra información está en mi carpeta de trabajo igual.

dropbox/CARPETAS_TRABAJO/dega/datos_participantes_lancis_sin_cvu.xlsx

**Comment by edithvilla** [comment]
@Didigar ya rellené las columnas en el archivo "datos_participantes_lancis_sin_cvu.xlsx" y ya está sincronizado

**Comment by Didigar** [comment]
@PaolaGomezPriego 
La hoja final de excel con los datos de todos los que no tenemos cvu ya está cargada dropbox/ADMIN/propuestas/conacyt/consolidacion_ln_2018/lancis_cu
