### ISSUE TITLE
hacer plantilla y llenar formato concurrencias equipo para CONACYT propuesta laboratorios nacionales  #Lancis ADMIN

### ISSUE THREAD

**Issue by Didigar** [PaolaGomezPriego/planeacion-colaborativa#530]

**Comment by Didigar** [comment]
@ovisnigra 
Dejo la base de datos lo que llevamos, va a cambiar porque ahora mismo estamos comparando una existente digital, con una que pasamos de unas hojas.
Dejo los datos que llevamos que serán modificados, con los insumos que me mando Paola y Fidel de como debe ir la plantilla...
Se encuentra ubicado en:
dropbox/ADMIN/propuestas/bd_activos_lancis

**Comment by ovisnigra** [comment]
ya estoy trabajando en el formato. en una hora (maomeno) espero estarlo mandando

**Comment by Didigar** [comment]
@ovisnigra @serranoycandela @PaolaGomezPriego 
Ya está lista versión preliminar en excel, están en amarillo algunos que hay que confirmar ...

**Comment by Didigar** [comment]
LISTO ÚLTIMA VERSIÓN ARRIBA @PaolaGomezPriego @ovisnigra @serranoycandela

**Comment by Didigar** [comment]
@ovisnigra 
Ya cambió la ubicación del excel y los insumos aqui te la dejo
dropbox/ADMIN/propuestas/conacyt/consolidacion_ln_2018
ahi mismo pondre la forma para que quede registrada la solicitud

**Comment by ovisnigra** [comment]
chiro

**Comment by ovisnigra** [comment]
OK. En la misma ruta( `ADMIN/propuestas/conacyt/consolidacion_ln_2018` )

Entrego los siguientes archivos:
- **plantilla_bd_activos_lancis.xlsx** --> plantilla vacía para llenado de formato.  Tiene dos hojas, una para Relación de equipos y una para Relación de Espacio Físico e Instalaciones Especiales.
- **bd_activos_lancis.xlsx** --> La base de datos en el formato de la plantilla llenada con los datos originales llenados por Diana (el archivo original de Diana lo renombré **bd_activos_lancis_v0.xlsx,** mismo que eventualmente Diana moverá a la carpeta de auxiliares (si es que la quieren conservar, o bien, lo pueden eliminar).

**Comment by PaolaGomezPriego** [comment]
terminado
