### ISSUE TITLE
Crear la carpeta de OIPA en Dropbox #OIPA

### ISSUE THREAD

**Issue by Nayita** [PaolaGomezPriego/planeacion-colaborativa#547]
Actividades:
Avisar a Diana de la organización de carpetas.
Checar si la carpeta de doctorado ha sido respaldado.

**Comment by Nayita** [comment]
@Didigar 
Por solicitud de Paola, generé una nueva carpeta llamada OIPA en la raíz. En ella pondré las bases de datos y una carpeta de procesamiento dónde estarán las gráficas. Te lo aviso para que estés informada y sepas dónde buscar la información porque eventualmente la carpeta de Doctorado se va a eliminar de la carpeta de trabajo de Paola

**Comment by Nayita** [comment]
@Didigar 
Revisar la carpeta graficas en procesamiento, las siguientes carpetas:
dgira_deleg_edo. No hay html ni Rmd
figure_html en carpetas gr_mia_dgira_files y gr_mia_disponibilidad_files. Están vacías
regi_part_edo. No hay html
resol_noresol. No hay html ni Rmd
Actualiza la información en OIPA por favor.
Gracias.
Saludos

**Comment by Didigar** [comment]
@Nayita 
Ya gregué los Rmd que son los que me parecen más importantes que los html....
queda pendiente generarlos a partir del Rmd

**Comment by Nayita** [comment]
@Didigar 
Perfecto cierro el issue. Genera los html y los pones por favor en cuanto estén. Los html son importantes para el repositorio finalmente.
