### ISSUE TITLE
Revisar los discos duros y registrar contenido #organización APC

### ISSUE THREAD

**Issue by Nayita** [PaolaGomezPriego/planeacion-colaborativa#568]

**Comment by edithvilla** [comment]
@Nayita ya revisé el registro de los discos duros que tu hiciste, y también registré mi nombre en las carpetas que soy responsable, también registré el nombre de Marco en algunas en las que él fue el responsable de hacer respaldo

Voy a agregar el registro de dos discos más:
Adata-MEGADAPT
WD-Invasoras

**Comment by edithvilla** [comment]
@Nayita 
ya agregué los registros de los discos duros externos que tengo, el lunes 12 te paso el disco duro externo WD-Invasoras

**Comment by Nayita** [comment]
Falta terminar de registrar tamaño y fecha de modificación

**Comment by Nayita** [comment]
Concluido
