### ISSUE TITLE
Crear la estructura de archivos para la presentación de sacmex #MEGADAPT

### ISSUE THREAD

**Issue by edithvilla** [PaolaGomezPriego/planeacion-colaborativa#591]
@serranoycandela @PaolaGomezPriego @aleestrada @Nayita @ovisnigra 

ya está creada la carpeta para la presentación de sacmex

PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018

**Comment by edithvilla** [comment]
voy a agregar en la carpeta de insumos:
1. plantilla del guión
2. insumos originales que nos proporcionó sacmex (pdf, banco de datos, capas geográficas)

**Comment by edithvilla** [comment]
@PaolaGomezPriego 
Ya están lista la carpeta de sacmex, en la carpeta de insumos.
También coloqué en la raíz de la carpeta: "pr_megadapt_sacmex_20feb2018" el README.txt, en donde coloqué la lista de capas geográficas que consultamos para hacer la capa de Red de desalojo.

**Comment by edithvilla** [comment]
@yosunemiquela 

ya está creada la carpeta para la presentación de sacmex

PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018

**Comment by yosunemiquela** [comment]
OK. Generé una carpeta en insumos con mi nombre en :

PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018/insumos/ymiquelajauregui
