### ISSUE TITLE
Dar formato a las gráficas de encharcamientos en Illustrator para presentación SACMEX #megadapt

### ISSUE THREAD

**Issue by PaolaGomezPriego** [PaolaGomezPriego/planeacion-colaborativa#600]
@yosunemiquela aquí puedes poner la ubicación del script

**Comment by yosunemiquela** [comment]
MEGADAPT/mega_carpetas_trabajo/Yosune/Inundaciones/Inundaciones.R

**Comment by Nayita** [comment]
El script no tenía banco de datos. Se corrigieron las gráficas desde Illustrator.
Actividad concluida
