### ISSUE TITLE
Crear Jsons para presentación SACMEX #megadapt

### ISSUE THREAD

**Issue by PaolaGomezPriego** [PaolaGomezPriego/planeacion-colaborativa#607]
poner ubicación aquí

**Comment by PaolaGomezPriego** [comment]
@aleestrada: poner en PRESENTACIONES\pr_megadapt_sacmex_20feb2018\insumos\aestrada  la capa de unidades económicas

**Comment by PaolaGomezPriego** [comment]
Edith: crea la capa de densidad de unidades económicas también.

**Comment by aleestrada** [comment]
Ya se agregaron en la carpeta indicada, los archivos de la capa de unidades económicas

**Comment by PaolaGomezPriego** [comment]
@serranoycandela para que veas ubicación

**Comment by edithvilla** [comment]
@serranoycandela @PaolaGomezPriego 

ya estan los Json de los nodos (lluvias y secas) y la red (lluvias y secas)

pr_megadapt_sacmex_20feb2018\insumos\fserrano\

**Comment by edithvilla** [comment]
@serranoycandela @PaolaGomezPriego

ya estan el Json de las ue_densidad, 

pr_megadapt_sacmex_20feb2018\insumos\fserrano\ue_densidad

**Comment by edithvilla** [comment]
issue concluido

**Comment by edithvilla** [comment]
se necesita actualizar las capas de nodos con la modificación que se agregaron
