### ISSUE TITLE
Averiguar dónde se encuentra la figura del modelo de integración #MEGADAPT

### ISSUE THREAD

**Issue by edithvilla** [PaolaGomezPriego/planeacion-colaborativa#624]
@ovisnigra en donde se encuentra la última versión de la figura del modelo de integración  de megadapt
 la busqué en 
Diseño gráfico LANCIS (Respaldo Sergio)/Megadapt IAI/Figuras generales Megadapt (Informes & Presentaciones)/Integración de modelos/fi_megadapt_integracion_modelos.png

esta figura no corresponde a la figura que insertaste en la presentación para sacmex

**Comment by ovisnigra** [comment]
Es la misma figura que mencionas, sólo que hice una adaptación para la presentación de SACMEX, el único cambio es que puse las leyendas abajo a la izquierda, nada más cambió. Este ajuste lo hice en el PPT mismo la figura no ha sido modificada en realidad.

**Comment by edithvilla** [comment]
OK, ENTERADA
