### ISSUE TITLE
proveer plantilla de entrega de bancos de datos #organizacion_apc

### ISSUE THREAD

**Issue by PaolaGomezPriego** [PaolaGomezPriego/planeacion-colaborativa#630]
@aleestrada @yosunemiquela

**Comment by edithvilla** [comment]
@abaezacastro @yosunemiquela 
aquí está el archivo para llenar los metadatos de la información

MEGADAPT/mega_layers/FormatoEntregaDatos.xls

deben renombrar el archivo:

metados_nombre_de_capa_fecha.xls
