### ISSUE TITLE
Respaldar en el Dropbox la propuesta de PAPIIT #ADMIN

### ISSUE THREAD

**Issue by Nayita** [PaolaGomezPriego/planeacion-colaborativa#639]
@dpedroza74 
En esta ruta ADMIN/propuestas/papiit del dropbox ya existe la carpeta papiit_2018 donde puedes colocar todos los documentos de la entrega final de la propuesta.
Avísame si tienes alguna duda de organización para el respaldo.
Notifica cuando ya lo hayas hecho. Gracias
Saludos

**Comment by dpedroza74** [comment]
Ya está
